# AIM ---------------------------------------------------------------------
# to test the tool I will simulate a bulk dataset generated by aggregating counts from a single cell dataset

# libraries ---------------------------------------------------------------
library(Seurat)
library(tidyverse)

# read in the data --------------------------------------------------------
# for this dataset I am using a dataset taken from the literature that already has the annotaiton
sobj <- readRDS("/mnt/SSD01/training/routines/scRNAseq/R/Seurat/out/object/100_ifnb_DonorStim.rds")

# explore the metadata
sobj@meta.data

# plot the dataset with the relative annotaiton
DimPlot(sobj,group.by = "seurat_annotations")

# save the metadata
saveRDS(sobj@meta.data,"../out/object/meta_sobj_100_ifnb.rds")

# save the raw counts per cell as sparse matrix
# The new version v2.2 now supports input of dgMatrix as the input of scRNA-seq reference.
sobj@assays$RNA$counts %>%
  saveRDS("../out/object/rawCountDense_sobj_100_ifnb.rds")

# wraingling --------------------------------------------------------------
# create a new covarite to include all the samples
sobj$test <- "all"

# generate one single pseudobulk for the whole dataset
cts_sample_all <- AggregateExpression(object = sobj,
                                      group.by = "test",
                                      assays = 'RNA',
                                      slot = "counts",
                                      return.seurat = FALSE)

# generate the count matrix
counts_all <- cts_sample_all$RNA %>%
  as.data.frame()

# save the table
counts_all %>%
  saveRDS("../out/object/rawCount_pBulk_all_100_ifnb.rds")

# do the same but split by treatment
# generate one single pseudobulk for the whole dataset
cts_sample_treat <- AggregateExpression(object = sobj,
                                        group.by = "stim",
                                        assays = 'RNA',
                                        slot = "counts",
                                        return.seurat = FALSE)

# generate the count matrix
counts_treat <- cts_sample_treat$RNA %>%
  as.data.frame()

# save the table
counts_treat %>%
  saveRDS("../out/object/rawCount_pBulk_treat_100_ifnb.rds")

# do the same but split by donor
# generate one single pseudobulk for the whole dataset
cts_sample_donor <- AggregateExpression(object = sobj,
                                        group.by = "donor_id_fix",
                                        assays = 'RNA',
                                        slot = "counts",
                                        return.seurat = FALSE)

# generate the count matrix
counts_donor <- cts_sample_donor$RNA %>%
  as.data.frame()

# save the table
counts_donor %>%
  saveRDS("../out/object/rawCount_pBulk_donor_100_ifnb.rds")

# do the same but split by cell type
# generate one single pseudobulk for the whole dataset
cts_sample_cellid <- AggregateExpression(object = sobj,
                                         group.by = "seurat_annotations",
                                         assays = 'RNA',
                                         slot = "counts",
                                         return.seurat = FALSE)

# generate the count matrix
counts_cellid <- cts_sample_cellid$RNA %>%
  as.data.frame()

# save the table
counts_cellid %>%
  saveRDS("../out/object/rawCount_pBulk_cellid_100_ifnb.rds")
