# REF ---------------------------------------------------------------------
# Pan-human Azimuth (AzimuthAPI) — intro vignette as a runnable script
# Source: https://satijalab.org/pan_human_azimuth/r/articles/intro_azimuthapi_vignette

# This vignette demonstrates how to install and use AzimuthAPI, an interface for cell type annotation using the Pan-human Azimuth neural network.
# The API takes a Seurat object and returns hierarchical cell type predictions, confidence scores, and low-dimensional embeddings useful for visualization.

# ---- Install AzimuthAPI -----------------------------------------------------
# "The Pan-human Azimuth R API, `AzimuthAPI`, is available for installation via Github:"
# remotes::install_github("satijalab/AzimuthAPI")

# ---- Load packages & data ---------------------------------------------------
library(AzimuthAPI)
library(Seurat)
library(SeuratData)
library(tidyverse)
library(presto)

# list all the reference available
AvailableData()

# For this vignette, we will demonstrate annotating a dataset of human bone marrow mononuclear (BMNC) cells that we published as part of Stuart, Butler et al Cell 2019. (https://doi.org/10.1016/j.cell.2019.05.031)
# This dataset is available through `SeuratData`.
# InstallData("bmcite")

# Load the data from `SeuratData`. Here we also make sure to normalize the data before running Pan-human Azimuth.
bmcite <- LoadData("bmcite")

# perform standard log-normalization with the NormalizeData function prior to annotating.
# Variable gene selection is not required; users should keep all quantified genes in the object prior to annotation.
bmcite <- NormalizeData(bmcite)

# explore the dataset
bmcite
bmcite@meta.data %>% head()

# ---- Annotate a dataset with Pan-human Azimuth ------------------------------
# Users have two options for running Pan-human Azimuth on their dataset: cloud-based or local.
# The cloud-based option is the easiest to use, and requires no additional setup.
# The local option requires setting up a Python environment with panhumanpy (Python package for the Pan-human Azimuth neural network) and its dependencies.
# Annotation results, regardless of the method used, are stored in the Seurat object as cell-level metadata, and the embeddings generated by the underlying neural network are stored in a new Seurat reduction.

# Option 1: run `CloudAzimuth`
# The `CloudAzimuth` function runs Pan-human Azimuth cell type annotation on a Seurat object via a cloud-based API deployed on AWS.

# time the process
t_init <- Sys.time()
bmcite_ann <- CloudAzimuth(bmcite)
t_end <- Sys.time()
# time
t_end - t_init

# save the object
saveRDS(bmcite_ann,file = "../out/object/00_bmcite_ann_remote.rds")

# explore the object after the annotation
bmcite_ann
bmcite_ann@meta.data %>% head()
bmcite_ann@reductions

# Option 2: run `ANNotate` (requires panhumanpy in a Python env reticulate can see)
# "First, set up a local Python environment:"
# # Create and activate conda environment:
# #   conda create -n pan-human-azimuth python=3.9
# #   conda activate pan-human-azimuth
# #   pip install panhumanpy
# "Then ask `reticulate` to use that environment:"
# library(reticulate)
# use_condaenv("pan-human-azimuth", required = TRUE)
# "Finally, run the `ANNotate` function to annotate your dataset."
# "Note that the initial run may take longer, as the model weights are downloaded
# and cached locally."
# bmcite_ann <- ANNotate(bmcite)

# ---- Examine model output ---------------------------------------------------
# Pan-human Azimuth returns predictions in multiple formats, as well as softmax probability scores to estimate model confidence.
# For more information on the output, see the reference.

# Inspect cell-level metadata returned by the model
# New columns - ex. final_level_labels, final_level_confidence, full_hierarchical_labels - have been added to the Seurat object metadata
md <- bmcite_ann@meta.data
colnames(md)

# are the false cells in the annotation correlated with the ones labelled as false in the full_consistent_hierarchy?
table(md$azimuth_broad,md$full_consistent_hierarchy)

# check the prop of score by consistency
md %>%
  ggplot(aes(x=full_consistent_hierarchy,y=final_level_confidence)) + geom_boxplot()

# We can view a histogram of softmax probabilities, which reflect the model confidence associated with each cell's annotation:
ggplot(md, aes(x = final_level_confidence)) +
  geom_histogram(bins = 20, fill = "skyblue") +
  labs(x = "Softmax probability", y = "Count",
       title = "Histogram of Softmax Probabilities") +
  theme_bw()

# As a QC / filtering step, we can remove cells with low scores:
bmcite_qc <- subset(bmcite_ann, final_level_confidence > 0.5)

# ---- Generate UMAP of Azimuth embeddings ------------------------------------
# Pan-human Azimuth provides embeddings of the encoding layer generated by the underlying neural network, stored in the `azimuth_embed` 128-dimensional reduction.
# We can use this to generate a two-dimensional visualization of the dataset, to examine cell type predictions in this low-dimensional space.

# Use azimuth_embed as input to generate UMAP
bmcite_qc <- RunUMAP(bmcite_qc, dims = 1:128,
                     reduction = "azimuth_embed",
                     reduction.name = "azimuth_umap")

bmcite_qc

# ---- Visualize predictions --------------------------------------------------
# The full_hierarchical_label for each cell provides the model's classification at each level of granularity, with different levels separated by the '|' character.
p2 <- DimPlot(bmcite_qc, group.by = "full_hierarchical_labels",
              label.size = 1.5, label = TRUE, reduction = "azimuth_umap",
              repel = TRUE) + NoLegend()
p2

# To avoid the long length of the full hierarchical label, we also output the final level of granularity in a separate column, `final_level_labels`, which is the last (most specific) level of the hierarchy for each cell.
p3 <- DimPlot(bmcite_qc, group.by = "final_level_labels",
              label.size = 2, label = TRUE, reduction = "azimuth_umap") +
  NoLegend()
p3

p4 <- FeaturePlot(bmcite_qc, features = "final_level_confidence",
                  reduction = "azimuth_umap")
p4

# We also postprocess our predictions to provide labels at three consistent levels of granularity for easy handling, marking any cell with an invalid full hierarchical label (based on `full_consistent_hierarchy`) as `False`.
# These categories provide a consistent level of granularity for each cell, but may differ from the `final_level_label`, either by forcing the model to predict further along the cell type hierarchy than its intial prediction, or by rolling back its prediction to a lower level of granularity.
p5 <- DimPlot(bmcite_qc, group.by = "azimuth_medium",
              label.size = 3, label = TRUE, reduction = "azimuth_umap") +
  NoLegend()
p5

p6 <- DimPlot(bmcite_qc, group.by = "azimuth_fine",
              label.size = 3, label = TRUE, reduction = "azimuth_umap") +
  NoLegend()
p6

# To remove the number of labels displayed, we can filter labels with less than a certain number of cells using `PrepLabel`.
# Here, we filter labels with less than 20 cells per label. This can be useful to filter outliers, especially as Pan-human Azimuth does not perform smoothing of single-cell labels by cluster. Therefore, a single outlier annotation for one cell will still display the outlier label on a visualization, and the `PrepLabel` function can help with this."
bmcite_qc <- PrepLabel(bmcite_qc, "azimuth_fine",
                       "azimuth_fine_filtered", cutoff = 20)
p7 <- DimPlot(bmcite_qc, group.by = "azimuth_fine_filtered",
              label.size = 3, label = TRUE, reduction = "azimuth_umap") +
  NoLegend()
p7

# ---- Visualize differentially expressed features ----------------------------
# The `make_azimuth_QC_heatmaps` function allows you to easily explore the quality of predicted labels by creating expression heatmaps by predicted cell type, with optional parameters for improved visualization.
# Plots are saved by `azimuth_broad` categories by default, with the exception of immune cell types grouped separately by lymphoid or myeloid/erythroid subpopulations.
plots <- make_azimuth_QC_heatmaps(bmcite_qc)
length(plots)

p8 <- plots[["Immune_Lymphoid cell_1"]]
p8

p9 <- plots[["Immune_Myeloid cell_1"]]
p9

# ---- More information --------------------------------------------------------
# For detailed options and usage of the `AzimuthAPI` functions, see the AzimuthAPI function reference."
# For another example of the usage of this package, see the Analysis and visualization of Visium HD data with cell segmentations vignette on the Seurat website.
